[package]
name = "crane-reg-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crane-test-dep = { registry = "alexandrie", version = "0.2" }
